apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-service-hpa
spec:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - external:
        metric:
          name: pubsub.googleapis.com|subscription|num_undelivered_messages
          selector:
            matchLabels:
              resource.labels.subscription_id: monitor-task-subscription
        target:
          type: AverageValue
          averageValue: 20
      type: External
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-service