apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: worker-service-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: worker-service
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: worker-service
        minAllowed:
          cpu: 250m
          memory: 256Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
        controlledResources: [ "cpu", "memory" ]
