name: Maven Package

on:
  push:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn clean install

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xvisox/worker-service
          tags: latest

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure GKE cluster access
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ vars.GKE_CLUSTER }}
          location: ${{ vars.GKE_LOCATION }}

      - name: Deploy to GKE
        run: kubectl apply -f .k8s/deployment.yaml

      - name: Deploy HPA to GKE
        run: kubectl apply -f .k8s/horizontal-scaling.yaml

      - name: Deploy VPA to GKE
        run: kubectl apply -f .k8s/vertical-scaling.yaml

